/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_nr_dbspec_Languages */

#ifndef _Included_no_nr_dbspec_Languages
#define _Included_no_nr_dbspec_Languages
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_nr_dbspec_Languages
 * Method:    dbspec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_no_nr_dbspec_Languages_dbspec
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
